language: php

php:
  - 7.3

# install phing globally
before_install:
  - phpenv rehash
  - source ~/.bashrc

before_script:
  - echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install
  - cp config.json.example config.json
  - phing build
  - cd -

script:
  - php vendor/bin/phpunit .
