language: php

php:
  - 7.3
env:
    global:
        - XDEBUG_MODE=coverage

before_script:
  - echo 'error_reporting = E_ALL' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install
  - cp config.json.example config.json
  - phing build
  - cd -

script:
  - php vendor/bin/phpunit .
